Fail fast and output debugging info whenever a test fails

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -2,4 +2,48 @@
 set -o errexit -o nounset -o pipefail
 cd "$(dirname "$0")/.."
 
-exec npx cucumber-js --publish-quiet "$@"
+RESET="\e[0m"
+BOLD="\e[1m"
+UNDERLINE="\e[4m"
+LRED="\e[91m"
+LGREEN="\e[92m"
+LMAGENTA="\e[95m"
+LCYAN="\e[96m"
+
+result=0
+
+# Build
+bin/build || result=$?
+
+# Run tests
+if [[ $result -eq 0 ]]; then
+    bin/cucumber --fail-fast "$@" || result=$?
+fi
+
+# If it failed, output debugging information
+if [[ -f jail/command.txt ]]; then
+    echo
+    echo -e "${LMAGENTA}${BOLD}${UNDERLINE}Command${RESET}"
+    cat jail/command.txt
+fi
+
+if [[ -f jail/stdout.txt ]]; then
+    echo
+    echo -e "${LGREEN}${BOLD}${UNDERLINE}Output${RESET}"
+    cat jail/stdout.txt
+fi
+
+if [[ -f jail/stderr.txt ]]; then
+    echo
+    echo -e "${LRED}${BOLD}${UNDERLINE}Errors${RESET}"
+    cat jail/stderr.txt
+fi
+
+if [[ -f jail/debug.txt ]]; then
+    echo
+    echo -e "${LCYAN}${BOLD}${UNDERLINE}Debug log${RESET}"
+    cat jail/debug.txt
+fi
+
+# Return the result code
+exit $result
